# Generated by Django 5.2.5 on 2025-08-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('price_250g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за 250 г')),
                ('price_500g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за 500 г')),
                ('price_1000g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за 1000 г')),
                ('acidity', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5', verbose_name='Кислотность (1-5)')),
                ('bitterness', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5', verbose_name='Горчинка (1-5)')),
                ('intensity', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5', verbose_name='Насыщенность (1-5)')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Кофе',
            },
        ),
    ]
