# Generated by Django 5.2.5 on 2025-09-01 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('manufacturer', models.CharField(choices=[('manufacturer1', 'Производитель 1'), ('manufacturer2', 'Производитель 2')], default='manufacturer1', max_length=20, verbose_name='Производитель')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Сироп',
                'verbose_name_plural': 'Сиропы',
            },
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('tea_type', models.CharField(choices=[('black', 'Черный'), ('green', 'Зеленый')], default='black', max_length=10, verbose_name='Вид чая')),
                ('price_50g', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за 50 г')),
                ('price_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за 100 г')),
            ],
            options={
                'verbose_name': 'Чай',
                'verbose_name_plural': 'Чай',
            },
        ),
        migrations.AddField(
            model_name='coffee',
            name='coffee_type',
            field=models.CharField(choices=[('arabica', 'Арабика'), ('robusta', 'Робуста'), ('blend', 'Смесь')], default='arabica', max_length=10, verbose_name='Сорт кофе'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='acidity',
            field=models.PositiveSmallIntegerField(default=3, help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Кислотность (1-5)'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='bitterness',
            field=models.PositiveSmallIntegerField(default=3, help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Горчинка (1-5)'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='intensity',
            field=models.PositiveSmallIntegerField(default=3, help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Насыщенность (1-5)'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price_1000g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за 1000 г'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price_250g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за 250 г'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price_500g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за 500 г'),
        ),
    ]
