# Generated by Django 5.2.5 on 2025-09-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_syrup_tea_coffee_coffee_type_alter_coffee_acidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syrup',
            name='manufacturer',
            field=models.CharField(choices=[('manufacturer1', 'Monin'), ('manufacturer2', 'Barinoff')], default='manufacturer1', max_length=20, verbose_name='Monin'),
        ),
    ]
