# Generated by Django 5.2.5 on 2025-09-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_syrup_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea',
            name='price_50g',
        ),
        migrations.AddField(
            model_name='tea',
            name='price_500g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за 500 г'),
        ),
    ]
