# Generated by Django 5.2.5 on 2025-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_tea_price_50g_tea_price_500g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syrup',
            name='manufacturer',
            field=models.CharField(choices=[('manufacturer1', 'Monin'), ('manufacturer2', 'Barinoff')], default='manufacturer1', max_length=20, verbose_name='Производитель'),
        ),
    ]
