# Generated by Django 5.2.5 on 2025-10-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_coffee_id_alter_syrup_id_alter_tea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images/', verbose_name='Изображение'),
        ),
    ]
