# Generated by Django 5.2.5 on 2025-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_coffee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tea_images/', verbose_name='Изображение'),
        ),
    ]
