# Generated by Django 5.2.5 on 2025-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_tea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='syrup_images/', verbose_name='Изображение'),
        ),
    ]
